import assert from 'node:assert/strict';
import {mkdir, stat, writeFile} from 'node:fs/promises';
import {resolve} from 'node:path';
const {chromium} = await import(process.env.PLAYWRIGHT_MODULE || 'playwright');
const evidence = resolve(process.env.EVIDENCE_DIR || '.omo/evidence/research-visuals');
await mkdir(evidence, {recursive:true});
const browser = await chromium.launch({headless:true, executablePath:process.env.BROWSER_PATH, args:['--no-proxy-server']});
const results = [];
const errors = [];
try {
  for (const lang of ['ko', 'en']) for (const viewport of [{width:1280,height:800}, {width:768,height:1024}, {width:375,height:667}]) {
    const page = await browser.newPage({viewport, hasTouch:viewport.width <= 768, recordVideo:{dir:evidence, size:viewport}});
    page.on('pageerror', error => errors.push(String(error)));
    const base = process.env.TEST_URL || 'http://127.0.0.1:4173/dist/';
    await page.goto(`${base}${lang === 'en' ? 'en/' : ''}?lang=${lang}`);
    await page.waitForFunction(() => document.querySelector('.image-dialog') && document.querySelector('.deck-page'));
    const prefix = `${lang}-${viewport.width}`;
    const capture = name => page.screenshot({path:`${evidence}/${prefix}-${name}.png`});
    const ids = () => page.locator('[id]').evaluateAll(elements => elements.map(element => element.id));
    const initialIds = await ids();
    assert.equal(new Set(initialIds).size, initialIds.length, 'IDs must be unique before interaction');
    const target = await page.evaluate(() => slides.findIndex(slide => [...slide.querySelectorAll('.evidence-media')].some(anchor => !anchor.closest('[data-clinical-scene]'))));
    assert(target >= 0, 'Deck must contain an actual image anchor');
    await page.evaluate(index => go(index, true), target);
    await page.waitForTimeout(110);
    assert(await page.locator('.is-current .evidence-reveal-mask').count() > 0, 'Current image must have a real mask during entry');
    await capture('reveal-mid');
    await page.evaluate(() => go(Math.min(current + 1, slides.length - 1), true));
    assert.equal(await page.locator('[data-slide]:not(.is-current) .evidence-reveal-mask').count(), 0, 'New navigation removes outgoing masks immediately');
    await page.waitForTimeout(820);
    await page.evaluate(index => go(index, false), target);
    const anchor = page.locator('.is-current .evidence-media').first();
    await anchor.locator('img').evaluate(image => image.decode());
    await anchor.focus();
    await page.keyboard.press('Enter');
    const dialog = page.locator('.image-dialog');
    await page.waitForFunction(() => document.querySelector('.image-dialog').open);
    assert.equal(await page.evaluate(() => document.activeElement.matches('.image-dialog-close')), true);
    assert.equal(await dialog.locator('img').getAttribute('src'), await anchor.getAttribute('href').then(href => new URL(href, page.url()).href));
    assert.equal(await dialog.locator('.image-dialog-caption').textContent(), await anchor.evaluate(node => node.closest('figure').querySelector('figcaption').textContent.trim()));
    await page.waitForTimeout(100);
    await capture('zoom-mid');
    await page.keyboard.press('Escape');
    await page.waitForFunction(() => !document.querySelector('.image-dialog').open);
    assert.equal(await anchor.evaluate(node => node === document.activeElement), true, 'Escape returns keyboard focus after interrupted opening');
    await anchor.click();
    await page.waitForTimeout(480);
    const fit = await dialog.locator('img').evaluate(image => {
      const rect = image.getBoundingClientRect();
      return {left:rect.left, top:rect.top, right:rect.right, bottom:rect.bottom, width:rect.width, height:rect.height, naturalWidth:image.naturalWidth, naturalHeight:image.naturalHeight};
    });
    assert(fit.left >= 0 && fit.top >= 0 && fit.right <= viewport.width && fit.bottom <= viewport.height, 'Original image fits viewport');
    assert(Math.abs(fit.width / fit.height - fit.naturalWidth / fit.naturalHeight) < .01, 'Zoom preserves original image ratio');
    await capture('zoom-open');
    const currentSlide = await page.evaluate(() => current);
    await page.mouse.wheel(0, 180);
    await page.keyboard.press('PageDown');
    assert.equal(await page.evaluate(() => current), currentSlide, 'Viewer owns input and prevents background navigation');
    await page.mouse.click(2, 2);
    await page.waitForFunction(() => !document.querySelector('.image-dialog').open);
    assert.equal(await anchor.evaluate(node => node === document.activeElement), true, 'Backdrop returns focus');
    const modifier = await anchor.evaluate(node => {
      const click = new MouseEvent('click', {bubbles:true, cancelable:true, ctrlKey:true});
      let intercepted;
      document.addEventListener('click', event => { intercepted = event.defaultPrevented; event.preventDefault(); }, {once:true});
      node.dispatchEvent(click);
      return {open:document.querySelector('.image-dialog').open, intercepted};
    });
    assert.deepEqual(modifier, {open:false, intercepted:false}, 'Modifier click preserves native link behavior');
    await anchor.click();
    await page.waitForTimeout(80);
    await page.emulateMedia({reducedMotion:'reduce'});
    await page.waitForFunction(() => document.querySelector('.image-dialog-image').getAnimations().length === 0, null, {timeout:200});
    assert.equal(await dialog.locator('img').evaluate(image => image.getAnimations().length), 0, 'Reduced motion settles running zoom');
    await dialog.locator('button').click();
    assert.equal(await dialog.evaluate(node => node.open), false, 'Reduced-motion close is immediate');
    await page.evaluate(index => { go(Math.max(0, index - 1), false); go(index, true); }, target);
    assert.equal(await page.locator('.evidence-reveal-mask').count(), 0, 'Reduced motion never masks content');
    await anchor.click();
    assert.equal(await dialog.locator('img').evaluate(image => image.getAnimations().length), 0, 'Reduced-motion open is immediate');
    await capture('reduced-motion');
    await dialog.locator('button').click();
    await page.emulateMedia({reducedMotion:'no-preference'});
    await page.evaluate(() => new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve))));
    const routeIndex = await page.evaluate(() => slides.findIndex(slide => slide.querySelector('.clinical-route')));
    assert(routeIndex >= 0, 'Deck contains clinical route');
    await page.evaluate(index => { go(index === 0 ? 1 : index - 1, false); go(index, true); }, routeIndex);
    await page.waitForTimeout(90);
    const route = await page.locator('.is-current .clinical-route li').evaluateAll(stages => stages.map(stage => ({opacity:Number(getComputedStyle(stage).opacity), animations:stage.getAnimations().length})));
    assert(route.some(stage => stage.animations), 'Clinical stages animate once on entry');
    await capture('route-mid');
    await page.waitForTimeout(820);
    assert.equal(await page.locator('.clinical-route li').evaluateAll(stages => stages.flatMap(stage => stage.getAnimations()).length), 0, 'Route emphasis finishes within 760ms');
    await capture('route-settled');
    assert.deepEqual(await ids(), initialIds, 'Interactions never clone source IDs');
    await page.evaluate(index => go(index, false), target);
    if (viewport.width <= 768) {
      const touch = await page.context().newCDPSession(page);
      const box = await anchor.boundingBox();
      const point = {x:box.x + box.width / 2, y:box.y + box.height / 2, radiusX:5, radiusY:5, force:1};
      await touch.send('Input.dispatchTouchEvent', {type:'touchStart', touchPoints:[point]});
      for (let step = 1; step <= 6; step++) {
        await touch.send('Input.dispatchTouchEvent', {type:'touchMove', touchPoints:[{...point, y:point.y - step * 20}]});
        await page.waitForTimeout(20);
      }
      await touch.send('Input.dispatchTouchEvent', {type:'touchEnd', touchPoints:[]});
      assert.equal(await page.evaluate(() => current), target + 1, 'One swipe from image advances exactly one slide');
      assert.equal(await dialog.evaluate(node => node.open), false, 'Swipe must not activate image link');
      await page.waitForTimeout(820);
      await capture('touch-swipe');
      await page.evaluate(index => go(index, false), target);
      const tapBox = await anchor.boundingBox();
      await page.touchscreen.tap(tapBox.x + tapBox.width / 2, tapBox.y + tapBox.height / 2);
      await page.waitForFunction(() => document.querySelector('.image-dialog').open);
      await dialog.locator('button').tap();
      await page.waitForFunction(() => !document.querySelector('.image-dialog').open);
      assert.equal(await anchor.evaluate(node => node === document.activeElement), true, 'Tap-open viewer closes back to image');
      await touch.detach();
    }
    for (const source of ['research-imaging','research-signals']) {
      await page.evaluate(id => navigateTo(document.getElementById(id), false), source);
      const concept = page.locator('.is-current .research-illustration .evidence-media');
      await concept.locator('img').evaluate(image => image.decode());
      await concept.click();
      await page.waitForFunction(() => document.querySelector('.image-dialog').open);
      assert.equal(await dialog.locator('img').getAttribute('src'), await concept.getAttribute('href').then(href => new URL(href,page.url()).href));
      assert.match(await dialog.locator('.image-dialog-caption').innerText(), /AI 생성|AI-generated/);
      await page.waitForTimeout(480);
      await capture(`${source}-concept`);
      await page.keyboard.press('Escape');
      await page.waitForFunction(() => !document.querySelector('.image-dialog').open);
      assert.equal(await concept.evaluate(node => node === document.activeElement), true);
    }
    await page.evaluate(index => go(index, false), target);
    await anchor.click();
    await page.waitForTimeout(80);
    await page.setViewportSize({width:viewport.width, height:viewport.height - 20});
    await page.waitForTimeout(180);
    assert.equal(await page.locator('.image-dialog-image').evaluate(image => image.getAnimations().length), 0, 'Resize cancels zoom safely');
    await capture('resize-settled');
    if (await dialog.evaluate(node => node.open)) await dialog.locator('button').click();
    await page.close();
    const videoPath = `${evidence}/${prefix}-motion.webm`;
    await page.video().saveAs(videoPath);
    await page.video().delete();
    assert((await stat(videoPath)).size > 0, 'Motion recording must be nonempty');
    results.push({lang, viewport, passed:true, video:videoPath, scenarios:['entry reveal', 'next-slide cancellation', 'Enter open', 'original image and caption', 'Escape mid-open', 'focus return', 'image fit', 'overlay wheel/keyboard', 'backdrop close', 'modifier link', 'reduced motion toggle/open/close', 'staged clinical route', 'unique IDs', 'resize cancellation', ...(viewport.width <= 768 ? ['real touch swipe from image advances once', 'touch tap opens image'] : [])], captures:`${prefix}-*.png`});
  }
  assert.deepEqual(errors, []);
  await writeFile(`${evidence}/results.json`, JSON.stringify({passed:true, results, errors}, null, 2));
  console.log(JSON.stringify({passed:true, cases:results.length, evidence}));
} catch (error) {
  await writeFile(`${evidence}/results.json`, JSON.stringify({passed:false, results, errors, failure:String(error)}, null, 2));
  throw error;
} finally { await browser.close(); }
