import { content } from './content.mjs';
import { publications } from './publications.mjs';
import { patents } from './patents.mjs';
import { researchEvidence } from './research.mjs';
import { slideOverviews } from './slide-overviews.mjs';
import { scholarProfile } from './scholar.mjs';
import { scholarView } from './scholar-view.mjs';
import { clinicalScene } from './clinical-scenes.mjs';
import { identityLogo } from './identity.mjs';

const scholar = 'https://scholar.google.com/citations?user=prJCNYoAAAAJ&hl=en';
const profile = 'https://medicine.inha.ac.kr/medicine/9606/subview.do';
const arrow = '<span class="arrow" aria-hidden="true">↗</span>';
export const escape = (value) => String(value).replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;').replaceAll("'", '&#39;');
const lines = (value) => escape(value).replaceAll('\n', '<br>');
const link = (url, label, cls = 'text-link') => `<a class="${cls}" href="${escape(url)}">${escape(label)} ${arrow}</a>`;
const heading = (section) => `<div class="section-heading"><div><p class="eyebrow">${escape(section.label)}</p><h2>${lines(section.title)}</h2>${section.intro ? `<p>${escape(section.intro)}</p>` : ''}</div></div>`;

export function renderPage(lang, siteUrl, languageScript, stylesheet = 'styles.css') {
  const c = content[lang];
  const ko = lang === 'ko';
  const root = ko ? './' : '../';
  const pageUrl = new URL(ko ? './' : 'en/', siteUrl).href;
  const illustrations = new Set(['neurocad-triage-journey','neurocad-triage-clean','research-workflow-concept','research-twin-concept','research-precision-concept','mission-clinical-research','workflow-ct-comparison']);
  const asset = (name) => `${root}assets/${name}.${name === 'tmi-logo-film' ? 'mp4' : name === 'tmi-logo-video-poster' ? 'jpg' : illustrations.has(name) ? 'png' : 'webp'}`;
  const overviews = slideOverviews(lang, asset, escape);
  const overview = id => `<div class="slide-overview">${overviews[id]}</div>`;
  const patentRow = (p) => `<article class="patent rule-row"><time class="meta" datetime="${p.year}">${p.year}</time><div><p class="patent-number" lang="en">${p.number}<span class="patent-status" lang="${lang}">${ko ? (p.granted ? '등록공보' : '출원공개') : (p.granted ? 'Granted patent' : 'Published application')}</span></p><h3>${link(`https://patents.google.com/patent/${p.number}/${lang}`, p.title[lang], 'paper-title')}</h3><p class="meta" lang="ko">${escape(p.inventors)}</p>${p.related.length ? `<div class="cluster">${p.related.map(f=>link(`https://patents.google.com/patent/${f.number}/en`, `${f.number} · ${f.year} · ${ko ? (f.granted ? '미국 등록' : '국제출원 공개') : (f.granted ? 'US grant' : 'PCT publication')}`)).join('')}</div>` : ''}</div></article>`;
  const clinicalStudies = indices => indices.map(index => {
    const study = scholarProfile.studies[index];
    return `<article class="profile-study"><p class="eyebrow">${escape(study.journal)}</p><h3>${escape(study[lang].title)}</h3><p>${escape(study[lang].body)}</p><a class="text-link" href="https://scholar.google.com/citations?view_op=view_citation&amp;hl=en&amp;user=prJCNYoAAAAJ&amp;citation_for_view=prJCNYoAAAAJ:${study.citation}" target="_blank" rel="noopener noreferrer" aria-label="${escape(study.title)} (${ko ? '새 탭' : 'new tab'})">${ko ? '관련 논문' : 'View publication'} ${arrow}</a></article>`;
  }).join('');
  const title = ko ? 'TMI-lab | Translational Medical Intelligence · 인하대학교 신기원' : 'TMI-lab | Translational Medical Intelligence · Inha University';
  const imageLabel = ko ? '연구 이미지 원본 보기' : 'View research image';
  const schema = { '@context': 'https://schema.org', '@type': 'ResearchOrganization', name: 'Translational Medical Intelligence Lab', alternateName: 'TMI-lab', url: siteUrl, email: 'kevinkwshin@inha.ac.kr', parentOrganization: { '@type': 'CollegeOrUniversity', name: 'Inha University' }, founder: { '@type': 'Person', name: 'Keewon Shin', jobTitle: 'Assistant Professor', sameAs: [scholar, 'https://orcid.org/0000-0002-5028-5716'] } };
  return `<!doctype html>
<html lang="${lang}">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>${escape(title)}</title><meta name="description" content="${escape(c.hero.description)}">
<meta name="theme-color" content="#1269b5">
<link rel="canonical" href="${pageUrl}">
<link rel="alternate" hreflang="ko" href="${siteUrl}"><link rel="alternate" hreflang="en" href="${new URL('en/', siteUrl).href}"><link rel="alternate" hreflang="x-default" href="${siteUrl}">
<meta property="og:image" content="${new URL('assets/tmi-logo.webp', siteUrl).href}"><meta property="og:image:alt" content="TMI-lab"><meta name="twitter:card" content="summary_large_image"><meta property="og:type" content="website"><meta property="og:site_name" content="TMI-lab"><meta property="og:title" content="${escape(title)}"><meta property="og:description" content="${escape(c.hero.description)}"><meta property="og:url" content="${pageUrl}"><meta property="og:locale" content="${ko ? 'ko_KR' : 'en_US'}">
<link rel="icon" href="${root}favicon.svg" type="image/svg+xml">
<script>document.documentElement.classList.add('js');</script>
<script>${languageScript}</script>
<link rel="stylesheet" href="${escape(root + stylesheet)}"><script src="${root}site.js" defer></script><script src="${root}deck.js" defer></script><script src="${root}visuals.js" defer></script><script src="${root}clinical-scenes.js" defer></script><script src="${root}identity.js?v=20261001-video" defer></script><script src="${root}scroll.js" defer></script>
<script type="application/ld+json">${JSON.stringify(schema).replaceAll('<', '\\u003c')}</script>
</head>
<body>
<a class="skip action" href="#main">${c.ui.skip}</a>
<header class="site-header"><div class="header-inner container">
<a class="brand" href="${root}" aria-label="${c.ui.home}"><span class="brand-title" lang="en"><span class="brand-mark">TMI-lab</span><span class="brand-expansion">(<span class="brand-initial">T</span>ranslational <span class="brand-initial">M</span>edical <span class="brand-initial">I</span>ntelligence)</span></span><span class="brand-description" lang="en">Inha University College of Medicine</span></a>
<nav class="nav" id="main-nav" aria-label="${ko ? '주 메뉴' : 'Main navigation'}">${c.nav.map(n => `<a href="#${n.id}">${n.label}</a>`).join('')}</nav>
<div class="header-controls"><div class="language" role="group" aria-label="${c.ui.language}"><a href="${root}?lang=ko" data-language="ko" lang="ko" aria-label="KO · 한국어" ${ko ? 'aria-current="page"' : ''}>KO</a><a href="${root}en/?lang=en" data-language="en" lang="en" aria-label="EN · English" ${!ko ? 'aria-current="page"' : ''}>EN</a></div><button class="menu-toggle" type="button" aria-controls="main-nav" aria-expanded="false" aria-label="${c.ui.menu}" data-open="${c.ui.menu}" data-close="${c.ui.close}"><span aria-hidden="true">☰</span></button></div>
</div><div class="reading-progress" aria-hidden="true"><span></span></div></header>
<main id="main">
<section class="hero container" id="welcome" data-slide="${ko ? '소개' : 'Welcome'}" aria-labelledby="hero-title">${overview('welcome')}<div class="slide-detail reading-content" id="detail-welcome" data-detail="welcome">
<div><p class="eyebrow">${c.hero.eyebrow}</p><h1 id="hero-title">${c.hero.titleLines.map(v => `<span>${escape(v)}</span>`).join('')}</h1><p class="hero-expansion" lang="en">Translational<br>Medical Intelligence</p><p class="hero-description">${escape(c.hero.description)}</p><div class="hero-actions cluster">${link('#translation', c.hero.primary, 'action')}${link('#research', c.hero.secondary)}</div><p class="hero-affiliation meta">${escape(c.footer.affiliation)}</p></div>
${identityLogo(lang,asset,escape,'hero-figure logo-figure')}
</div></section>
<section class="section translation-section" id="translation" data-slide="${ko ? '기술이전' : 'Translation'}">${overview('translation')}<div class="slide-detail reading-content" id="detail-translation" data-detail="translation"><div class="container">
${heading(c.translation)}
<div class="clinical-scene-reading">${clinicalScene('triage',lang,asset,escape)}</div>
<div class="neurocad-feature"><div class="neurocad-copy"><p class="eyebrow">Coreline Soft · 2024</p><h3 lang="en">AVIEW NeuroCAD</h3><p class="neurocad-subtitle">${ko ? '뇌출혈 의심 환자를 더 빠르게 확인하도록.' : 'Earlier review for suspected brain hemorrhage.'}</p><p>${ko ? '뇌 CT의 출혈 의심 부위와 출혈량을 분석해 의료진의 우선 판독을 지원합니다. 영상 분석을 응급 진료의 판단 흐름에 연결하는 기술입니다.' : 'Analyzes suspected hemorrhage and its volume in brain CT to prioritize review. Image-based triage supports faster clinical decisions when timely treatment matters.'}</p><ul class="clinical-impact"><li>${ko ? '100여 개 이상 응급실에서 사용' : 'Used in over 100 emergency departments'}</li><li>${link('https://corelinesoft.com/company/about-us/',ko ? '식약처 혁신의료기기 지정' : 'MFDS Innovative Medical Device designation')}</li></ul><div class="cluster">${link('https://doi.org/10.1016/j.media.2022.102489', ko ? '관련 연구 논문' : 'Related research')}</div></div><figure><img src="${asset('neurocad')}" width="1200" height="650" alt="${ko ? '코어라인소프트 AVIEW NeuroCAD의 뇌 CT 분석 화면' : 'Brain CT analysis interface of Coreline Soft AVIEW NeuroCAD'}" loading="lazy"><figcaption>${ko ? '제품 이미지: Coreline Soft · 공식 제품 소개' : 'Product image: Coreline Soft · official product page'}</figcaption></figure></div>
<div class="reading-content translation-evidence" id="translation-sources"><h3>${ko ? '도입 실적과 근거' : 'Adoption and evidence'}</h3><p>${ko ? '100여 개 이상 응급실 도입: 연구실 제공 자료, 2026년 9월 기준.' : 'Use in over 100 emergency departments: lab-provided information, September 2026.'}</p><p>${link('https://corelinesoft.com/en-gb/aview/brain/neurocad/', ko ? '제품 기능 및 인허가: 코어라인소프트 공식 소개' : 'Product features and regulatory information: Coreline Soft')}</p><p>${link('https://doi.org/10.1016/j.media.2022.102489', 'Medical Image Analysis · 2022')}</p><figure><img src="${asset('neurocad')}" width="1200" height="650" loading="lazy" alt="${ko ? 'AVIEW NeuroCAD 뇌 CT 분석 화면' : 'AVIEW NeuroCAD brain CT analysis'}"><figcaption>Coreline Soft · AVIEW NeuroCAD</figcaption></figure><p class="meta">${ko ? '첫 화면의 일러스트는 우선 판독 지원을 설명하는 AI 생성 개념도입니다. 위 이미지는 실제 제품 화면입니다.' : 'The opening illustration is an AI-generated concept of priority review. The image above shows the actual product.'}</p></div>
</div></div></section>
<section class="section translation-section" id="transfers" data-slide="${ko ? '기술이전 사례' : 'Transfer portfolio'}" data-nav="translation">${overview('transfers')}<div class="slide-detail reading-content" id="detail-transfers" data-detail="transfers"><div class="container">
<div class="section-heading"><h2>${ko ? '연구가 이어진 기술들' : 'A portfolio of translation'}</h2></div>
<div class="transfer-grid">${c.translation.items.filter(t => t.name !== 'AVIEW NeuroCAD').map(t => `<article class="transfer"><time class="meta">${t.year}</time><div><h3 lang="en">${escape(t.name)}</h3><span class="recipient">${escape(t.recipient)}</span><h4 class="transfer-impact">${escape(t.impact)}</h4><p>${escape(t.body)}</p>${t.source ? link(t.source,ko ? '비교 연구 읽기' : 'Read the comparative study') : ''}${t.name === 'AVIEW NeuroCAD' ? link('https://corelinesoft.com/en/aview/brain/neurocad/', ko ? '제품 소개' : 'About the product') : ''}</div></article>`).join('')}</div>
<div class="transfer-case-study" id="detail-clinical"><div class="clinical-feature" id="clinical"><figure><a class="scan-frame image-link" href="${asset('shoulder-landmarks')}" aria-label="${imageLabel}: GreyNet"><img src="${asset('shoulder-landmarks')}" width="800" height="956" loading="lazy" alt="${ko ? '어깨 Grashey X-ray에 연구자와 AI 모델의 해부학적 랜드마크를 표시한 원본 연구 이미지' : 'Shoulder Grashey radiograph with anatomical landmarks from readers and an AI model'}"></a><figcaption>${ko ? 'GreyNet · 촬영 품질 평가를 위한 어깨 X-ray 랜드마크' : 'GreyNet · Shoulder landmarks for image quality assessment'}</figcaption></figure><div class="feature-copy"><p class="eyebrow">${ko ? '영상 품질' : 'Image quality'}</p><h3>${ko ? '촬영실을 떠나기 전에,<br>영상 품질을 확인합니다.' : 'Check image quality<br>before the patient leaves.'}</h3><p>${ko ? 'GreyNet은 Grashey X-ray의 랜드마크를 검출해 촬영 자세와 품질을 확인하고, 필요 시 방사선사에게 즉시 재촬영을 요청하는 솔루션입니다. 촬영과 품질 확인을 한 흐름으로 연결하는 것이 핵심입니다.' : 'GreyNet detects landmarks in Grashey X-rays to check positioning and quality, requesting an immediate retake from the radiographer when needed. Its purpose is to connect acquisition and quality assurance in one workflow.'}</p>${link('https://doi.org/10.1002/mp.70285', ko ? '관련 논문 읽기' : 'Read the study')}</div></div></div>
</div></div></section>

<section class="section container mission-story" id="mission" data-slide="${ko ? '연구 철학' : 'Our mission'}">${overview('mission')}<div class="slide-detail reading-content" id="detail-mission" data-detail="mission">
<div class="mission-sticky"><p class="eyebrow">${c.intro.label}</p><h2>${lines(c.intro.title)}</h2><p class="mission-intro">${escape(c.intro.body)}</p><div class="mission-reading-illustration">${clinicalScene('mission',lang,asset,escape)}</div></div>
<div class="mission-chapters">${c.approach.steps.map((s,i)=>`<article class="mission-chapter" id="stage-${i+1}" data-chapter><span class="chapter-number" aria-hidden="true">0${i+1}</span><p class="eyebrow" lang="en">${['Clinical questions','Data & methods','Clinical evaluation'][i]}</p><h3>${escape(s.title)}</h3><p>${escape(s.body)}</p></article>`).join('')}</div>
</div></section>
${c.research.items.map((r,i)=>{ const evidence = researchEvidence[lang][i]; return `<section class="section research-section" id="${['research','research-imaging','research-signals'][i]}" data-slide="${ko ? ['임상 워크플로우','디지털 트윈','정밀의료'][i] : ['Clinical workflow','Digital twins','Precision medicine'][i]}" data-nav="research">${overview(['research','research-imaging','research-signals'][i])}<div class="slide-detail reading-content" id="detail-${['research','research-imaging','research-signals'][i]}" data-detail="${['research','research-imaging','research-signals'][i]}"><div class="container research-portfolio">
<div class="research-overview"><div><p class="eyebrow">${ko ? '연구 분야' : 'Research'}</p><h2>${ko ? '연구 목표' : 'Research goal'} ${i+1}. ${escape(r.title)}</h2><p class="research-question">${escape(r.question)}</p></div><div><p class="research-body">${escape(r.body)}</p><dl class="research-brief"><div><dt>${ko ? '연구 방법' : 'Methods'}</dt><dd>${escape(evidence.method)}</dd></div><div><dt>${ko ? '임상적 의의' : 'Clinical relevance'}</dt><dd>${escape(evidence.value)}</dd></div></dl></div></div>
<div class="clinical-scene-reading">${clinicalScene(['workflow','twin','precision'][i],lang,asset,escape)}</div>
<div class="research-study"><div class="study-intro"><h3>${escape(evidence.study)}</h3><p>${escape(evidence.note)}</p></div><div class="research-plates ${evidence.images.length > 1 ? 'paired' : ''}">${evidence.images.map(f=>`<figure class="research-plate"><a class="image-link" href="${asset(f.name)}" target="_blank" rel="noopener noreferrer" aria-label="${imageLabel}: ${escape(f.caption)} (${ko ? '새 탭' : 'opens in a new tab'})"><img src="${asset(f.name)}" width="${f.width}" height="${f.height}" alt="${escape(f.alt)}" loading="lazy"></a><figcaption>${escape(f.caption)}</figcaption></figure>`).join('')}</div>${i===2 ? link(asset('ecg-dcam-architecture'), ko ? 'DCAM 모델 구조 보기' : 'Explore the DCAM architecture') : ''}</div>
${i !== 1 ? `<div class="related-studies"><h3>${ko ? '관련 임상 연구' : 'Related clinical research'}</h3>${clinicalStudies(i === 0 ? [0,1] : [2])}</div>` : ''}</div></div></section>`;}).join('')}
<section class="section" id="publications" data-slide="${ko ? '논문' : 'Publications'}">${overview('publications')}<div class="slide-detail reading-content" id="detail-publications" data-detail="publications"><div class="container">
<div class="section-heading"><div><p class="eyebrow">${c.publications.label}</p><h2>${c.publications.title}</h2>${c.publications.intro ? `<p>${c.publications.intro}</p>` : ''}</div><a class="text-link" href="${scholar}" target="_blank" rel="noopener noreferrer" aria-label="${c.publications.all} (${ko ? '새 탭' : 'opens in a new tab'})">${c.publications.all} ${arrow}</a></div>
<div class="collection-preview">${publications.slice(0,3).map(p=>`<article class="preview-row"><p class="meta">${p.year} · ${escape(p.journal)}</p><h3>${link('https://doi.org/'+p.doi,p.title,'paper-title')}</h3></article>`).join('')}<button class="action" type="button" data-read="publication-content" data-title="${c.publications.title}">${ko ? '논문 목록 · 검색' : 'Browse & search publications'}</button></div>
<div class="reading-content" id="publication-content"><div class="publication-controls" hidden><div class="filters" role="group" aria-label="${ko ? '연구 분야 필터' : 'Filter by research area'}">${Object.entries(c.publications.filters).map(([key, label]) => `<button class="filter" type="button" data-filter="${key}" aria-pressed="${key === 'all'}">${label}</button>`).join('')}</div><div class="search-wrap"><label for="publication-search" class="sr-only">${c.publications.search}</label><input id="publication-search" class="search" type="search" placeholder="${c.publications.searchPlaceholder}" autocomplete="off"></div></div>
<p class="result-count meta" id="publication-count" role="status" aria-live="polite" data-format="${c.publications.results}">${c.publications.results.replace('{count}', String(publications.length))}</p>
<div class="publication-list">${publications.map(p => `<article class="publication rule-row" data-paper data-category="${p.category}"><time class="meta">${p.year}</time><div><h3><a class="paper-title" lang="en" href="https://doi.org/${escape(p.doi)}">${escape(p.title)}</a></h3><p class="meta" lang="en">${escape(p.authors)}</p><p class="journal meta"><span lang="en">${escape(p.journal)}</span> · ${escape(c.publications.filters[p.category])}</p></div><span class="arrow" aria-hidden="true">↗</span></article>`).join('')}</div>
<div class="empty-state" id="publication-empty" hidden><p>${c.publications.empty}</p><button class="filter" id="reset-publications" type="button">${c.publications.reset}</button></div>
</div></div></div></section>
<section class="section patents-section" id="patents" data-slide="${ko ? '특허' : 'Patents'}">${overview('patents')}<div class="slide-detail reading-content" id="detail-patents" data-detail="patents"><div class="container"><div class="section-heading"><div><p class="eyebrow">Patents</p><h2>${ko ? '특허' : 'Patents & applications'}</h2></div></div><div class="collection-preview">${patents.filter(p=>p.area==='medical').slice(0,3).map(p=>`<article class="preview-row"><p class="meta">${p.year} · ${p.number}</p><h3>${link(`https://patents.google.com/patent/${p.number}/${lang}`,p.title[lang],'paper-title')}</h3></article>`).join('')}<button class="action" type="button" data-read="patent-content" data-title="${ko ? '특허' : 'Patents'}">${ko ? '전체 특허 보기' : 'Browse all patents'}</button></div><div class="reading-content" id="patent-content"><div class="patent-list">${patents.filter(p=>p.area==='medical').map(patentRow).join('')}<details class="details"><summary>${ko ? '이전 산업 연구 특허' : 'Earlier industrial research patents'}</summary>${patents.filter(p=>p.area==='industry').map(patentRow).join('')}</details></div></div></div></div></section>
<section class="section people-section" id="people" data-slide="${ko ? '구성원' : 'People'}">${overview('people')}<div class="slide-detail reading-content" id="detail-people" data-detail="people"><div class="container">
${heading(c.people)}
<div class="profile-layout"><div class="profile-summary"><div class="profile-identity"><figure class="portrait-wrap"><img src="${asset('keewon-shin')}" width="640" height="795" loading="lazy" alt="${ko ? '신기원 교수' : 'Professor Keewon Shin'}"></figure><div><h3 class="profile-name">${c.people.name}</h3><p class="profile-role">${c.people.role}</p><p class="meta">${c.people.affiliation}</p></div></div><p class="profile-bio">${escape(c.people.bio)}</p><div class="profile-links cluster"><a class="text-link" href="${escape(scholar)}" target="_blank" rel="noopener noreferrer" aria-label="${ko ? 'Google Scholar (새 탭)' : 'Google Scholar (new tab)'}">Google Scholar ${arrow}</a>${link('https://github.com/kevinkwshin','GitHub')}${link('https://orcid.org/0000-0002-5028-5716','ORCID')}</div></div><details class="details profile-history" id="career" open><summary>${c.people.educationLabel} · ${c.people.careerLabel}</summary><div class="career-columns"><div><h4>${c.people.educationLabel}</h4><ul>${c.people.education.map(e=>`<li>${escape(e)}</li>`).join('')}</ul></div><div><h4>${c.people.careerLabel}</h4><ul>${c.people.career.map(e=>`<li>${escape(e)}</li>`).join('')}</ul></div></div>${link(profile,c.people.profileLink)}</details><aside class="profile-project" aria-labelledby="project-title"><h3 id="project-title">${ko ? '수행과제' : 'Research project'}</h3><p class="project-role">${ko ? '핵심연구A · 연구책임자' : 'Core Research A · Principal Investigator'}</p><p>${ko ? '건강진단의 멀티모달 추적관찰 데이터 기반 심혈관 질환 조기 예측 AI 시스템 개발' : 'Development of an AI system for early cardiovascular disease prediction using multimodal longitudinal health screening data'}</p></aside></div>
<section id="activity" class="activity-section"><h2>${ko ? '연구 활동' : 'Research activity'}</h2><div class="activity-grid">${scholarView(lang, escape)}</div></section>
</div></div></section>
<section class="section contact-section" id="contact" data-slide="${ko ? '연락처' : 'Contact'}">${overview('contact')}<div class="slide-detail reading-content" id="detail-contact" data-detail="contact"><div class="container contact-layout"><div><p class="eyebrow">${c.contact.label}</p><h2>${lines(c.contact.title)}</h2><p>${escape(c.contact.body)}</p></div><dl class="contact-details"><dt>${c.contact.emailLabel}</dt><dd><a href="mailto:kevinkwshin@inha.ac.kr">kevinkwshin@inha.ac.kr ${arrow}</a></dd><dt>${c.contact.locationLabel}</dt><dd>${escape(c.contact.location)}</dd></dl></div><footer class="footer container"><div><span>© 2026</span><p>${escape(c.footer.affiliation)}</p></div><p lang="en">Translational Medical Intelligence Lab<br>Inha University College of Medicine</p></footer></div></section>
</main>

<nav class="slide-controls" aria-label="${ko ? '섹션 이동' : 'Section navigation'}" hidden><span class="slide-position" aria-hidden="true">01 / 12</span><span class="slide-title">${ko ? '소개' : 'Welcome'}</span><button class="reading-toggle" type="button" data-reading aria-pressed="false" data-reading-label="${ko ? '연속 보기' : 'Read page'}" data-slides-label="${ko ? '슬라이드 보기' : 'Slide view'}">${ko ? '연속 보기' : 'Read page'}</button><button type="button" data-slide-prev aria-label="${ko ? '이전 섹션' : 'Previous section'}"><span aria-hidden="true">↑</span></button><button type="button" data-slide-next aria-label="${ko ? '다음 섹션' : 'Next section'}"><span aria-hidden="true">↓</span></button></nav>
<dialog class="reading-dialog" aria-labelledby="reading-title"><div class="dialog-header"><h2 id="reading-title"></h2><form method="dialog"><button class="filter" autofocus>${ko ? '닫기' : 'Close'}</button></form></div><div class="dialog-content"></div></dialog>
</body></html>`;
}
