export const researchEvidence = {
  ko: [
    { method: '영상 품질 평가 · 종단 판독문 분석 · LLM 오류 탐지', value: '반복 검토를 줄이고, 우선 확인할 정보를 진료 흐름 안에서 제시합니다.', study: '판독문을 시간의 흐름 속에서 읽다', note: '이전 검사와 추적 검사 사이의 오류를 검출하는 연구 설계입니다. 실제 진료 도입에 앞서 오류 유형별 성능과 위양성을 평가합니다.', images: [{name:'radiology-error-study',width:2014,height:638,caption:'추적관찰 영상의학 판독문의 오류 검출 연구 설계 · 발표자료 13쪽',alt:'추적 판독문 100쌍의 오류 삽입과 여섯 오류 유형별 LLM 및 영상의학과 의사 평가를 나타낸 연구 설계'}] },
    { method: '해부학적 랜드마크 · 종단 모델링 · 수술 결과 예측', value: '가능한 치료 시나리오를 비교하고, 수술 계획과 환자 상담을 위한 예측 근거를 연구합니다.', study: '해부학적 변화의 예측에서 수술 계획으로', note: '아래는 두부계측 성장예측의 기반 연구입니다. 수술 후 상태 예측과 치료 시나리오 비교는 이를 확장하는 연구 방향입니다.', images: [{name:'growth-prediction-errors',width:1434,height:320,caption:'성장예측 연구: 치료기간·장치 종류·연령에 따른 예측 오차 분포 · 발표자료 16쪽',alt:'치료기간, 장치 종류, 초기 및 추적 연령에 따른 평균 성장예측 오차를 밀리미터 단위로 나타낸 네 상자그림'}] },
    { method: '베이지안 불확실성 · 영상 정량화 · 생체신호 분석', value: '측정값과 신뢰도를 함께 해석해 환자별 위험 평가와 치료 반응 연구의 기반을 만듭니다.', study: '정밀한 측정, 신뢰할 수 있는 해석', note: '망막 혈관 분할과 심전도 분석은 정밀의료를 위한 기반 연구입니다. 질병의 조기 예측과 치료 선택으로 연결하는 방법을 연구합니다.', images: [{name:'retinal-vessels',width:1184,height:646,caption:'ProRetina · 베이지안 모델 적용에 따른 망막 혈관 분할 비교 · 발표자료 7쪽',alt:'베이지안 모델 적용 전후의 안저영상과 혈관 분할 결과를 비교한 연구 그림'},{name:'ecg-attention',width:1200,height:951,caption:'DCAM · 심전도 분석의 어텐션 맵 · 발표자료 30쪽',alt:'심전도 파형에서 모델이 주목하는 구간을 보여주는 DCAM 어텐션 맵'}] }
  ],
  en: [
    { method: 'Image quality · Longitudinal reports · LLM error detection', value: 'Surface information that warrants review within the clinical workflow, reducing repeated checks.', study: 'Reading radiology reports across time', note: 'This study evaluates errors between prior and follow-up reports. Error-specific performance and false positives are assessed before clinical use.', images: [{name:'radiology-error-study',width:2014,height:638,caption:'Longitudinal radiology report error-detection study design · Presentation, slide 13',alt:'Study design comparing an LLM and radiologists across six error types injected into 100 longitudinal report pairs'}] },
    { method: 'Anatomical landmarks · Longitudinal models · Outcome prediction', value: 'Study treatment scenarios to build predictive evidence for surgical planning and patient discussions.', study: 'From anatomical change to surgical planning', note: 'The figure shows foundational cephalometric growth-prediction research. Postoperative prediction and treatment-scenario comparison are directions for extending this work.', images: [{name:'growth-prediction-errors',width:1434,height:320,caption:'Growth prediction: error by treatment duration, appliance and age · Presentation, slide 16',alt:'Four box plots of mean growth-prediction error in millimeters by treatment duration, appliance type, baseline age and follow-up age'}] },
    { method: 'Bayesian uncertainty · Quantitative imaging · Biosignals', value: 'Interpret measurements alongside their reliability as a foundation for individual risk and treatment-response research.', study: 'Precise measurements, interpretable evidence', note: 'Retinal vessel segmentation and ECG analysis are foundations for precision medicine. We study how to connect these methods to early prediction and treatment decisions.', images: [{name:'retinal-vessels',width:1184,height:646,caption:'ProRetina · Vessel segmentation with Bayesian modeling · Presentation, slide 7',alt:'Retinal images and vessel segmentation maps comparing methods with and without Bayesian modeling'},{name:'ecg-attention',width:1200,height:951,caption:'DCAM · Attention maps for ECG analysis · Presentation, slide 30',alt:'ECG attention maps showing the waveform regions emphasized by DCAM'}] }
  ]
};
