import {scholarProfile} from './scholar.mjs';

export function scholarView(lang, escape) {
  const ko = lang === 'ko';
  const ceiling = Math.max(100, Math.ceil(Math.max(...scholarProfile.trend.map(point => point.count)) / 100) * 100);
  const checkedLabel = new Intl.DateTimeFormat(ko ? 'ko-KR' : 'en-US', {year:'numeric', month:'long', day:'numeric', timeZone:'UTC'}).format(new Date(`${scholarProfile.checked}T00:00:00Z`));
  return `<section class="profile-scholar"><h3>${ko ? '연구 프로필' : 'Research profile'}</h3><p lang="en">${scholarProfile.interests.map(escape).join(' · ')}</p><dl class="scholar-metrics"><div><dt>${ko ? '총 인용' : 'Citations'}</dt><dd>${scholarProfile.citations.toLocaleString('en-US')}</dd></div><div><dt>h-index</dt><dd>${scholarProfile.hIndex}</dd></div><div><dt>i10-index</dt><dd>${scholarProfile.i10Index}</dd></div></dl><p class="meta"><a href="${escape(scholarProfile.url)}" target="_blank" rel="noopener noreferrer">Google Scholar</a> · ${ko ? '전체 기간 · 확인일' : 'All time · Checked'} <time datetime="${scholarProfile.checked}">${scholarProfile.checked}</time></p></section>
<figure class="scholar-trend"><h3>${ko ? '연도별 인용 추세' : 'Citations by year'}</h3><ol class="citation-bars">${scholarProfile.trend.map(point => `<li aria-label="${point.year}: ${point.count} ${ko ? '회 인용' : 'citations'}"><span class="citation-column"><span>${point.count}</span><span class="citation-bar" style="--bar-size:${point.count / ceiling * 85}%" aria-hidden="true"></span></span><time datetime="${point.year}">${point.year}</time></li>`).join('')}</ol><figcaption><a href="${escape(scholarProfile.url)}" target="_blank" rel="noopener noreferrer">Google Scholar</a> · ${ko ? `${checkedLabel}까지 집계 · 당해 연도 집계 중` : `Through ${checkedLabel} · current year is partial`}</figcaption></figure>`;
}
